In [1]:
import numpy as np

(Matrix). With m, n ∈ N a real-valued (m, n) matrix A is
an m·n-tuple of elements aij , i = 1, . . . , m, j = 1, . . . , n, which is ordered
according to a rectangular scheme consisting of m rows and n columns:

In [2]:
# 3 x 2
A = np.array(
    [
        [1, 2, 3],
        [3, 2, 1]
    ]
)

# 2 x 3
B = np.array(
    [
        [0, 2],
        [0, -1],
        [0, 1],


    ]
)

AB = np.dot(A, B)
AB

array([[0, 3],
       [0, 5]])

In [4]:
BA = np.dot(B, A)
BA


array([[ 6,  4,  2],
       [-3, -2, -1],
       [ 3,  2,  1]])

## 🧠 **Matriz Quadrada, Inversa e Transposta**

$$
A = \begin{bmatrix}
2 & 1 \\
4 & 3
\end{bmatrix} \quad \text{(2 linhas × 2 colunas → quadrada)}
$$

### 🔷 **1. O que é uma matriz quadrada?**

Uma matriz é **quadrada** quando tem o **mesmo número de linhas e colunas**.
Exemplo:

---

### 🔁 **2. Transposta de uma Matriz**

A **transposta** de uma matriz $A$, escrita como $A^T$, é obtida **trocando as linhas pelas colunas**.

Exemplo:

$$
A = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\quad \Rightarrow \quad
A^T = \begin{bmatrix}
1 & 3 \\
2 & 4
\end{bmatrix}
$$

---


In [6]:
A.T, A

(array([[1, 3],
        [2, 2],
        [3, 1]]),
 array([[1, 2, 3],
        [3, 2, 1]]))


### 🔄 **3. Inversa de uma Matriz**

Se $A$ é uma **matriz quadrada**, sua **inversa** $A^{-1}$ é outra matriz tal que:

$$
A \cdot A^{-1} = I \quad \text{e} \quad A^{-1} \cdot A = I
$$

Onde $I$ é a **matriz identidade** (como o número 1 na multiplicação comum).

Exemplo da identidade $2×2$:

$$
I = \begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
$$

### ✅ Se essa inversa existe:

* Dizemos que a matriz é **invertível**, **regular**, ou **não singular**.

### ❌ Se **não** existe:

* Dizemos que a matriz é **não invertível**, **singular**, ou **irregular**.

> A inversa **só existe** para algumas matrizes. Nem toda matriz quadrada tem inversa.

---

Para:

$$
A = \begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

Se $ad - bc \ne 0$, então:

$$
A^{-1} = \frac{1}{ad - bc}
\begin{bmatrix}
d & -b \\
-c & a
\end{bmatrix}
$$

---

### 📌 Resumo dos termos:

| Termo               | Significado                         |
| ------------------- | ----------------------------------- |
| **Inversa (A⁻¹)**   | Matriz que "desfaz" a multiplicação |
| **Transposta (Aᵀ)** | Linhas viram colunas e vice-versa   |
| **Singular**        | Não possui inversa                  |
| **Nonsingular**     | Possui inversa                      |
| **Regular**         | Mesmo que nonsingular               |
| **Não invertível**  | Não tem inversa                     |
| **Invertível**      | Tem inversa                         |


In [ ]:
det = np.linalg.det(AB)
print(det)

if det != 0:
    print(np.linalg.inv(AB))

else:
    print('A matriz AB e singular (nao invertivel).')

np.float64(0.0)